config/routes.rb
Rails.application.routes.draw do
  get 'managed_files_usages/models'

  get 'managed_files_usages/usage'

  resources :managed_files

    get 'managed_files/file_object/:id' => 'managed_files#file_object'
    get 'managed_files/new' => 'managed_files#new'
    get 'managed_files_usages/models/:id' => 'managed_files_usages#models'
    get 'managed_files_usages/usage' => 'managed_files#usage'
    post 'managed_files/write_to_usage' => 'managed_files#write_to_usage'
    post 'managed_files/create' => 'managed_files#create'
    get 'managed_files/uploaded_file/:id' => 'managed_files#uploaded_file'

  root 'managed_files#new'

end

app/models/managed_file.rb
class ManagedFile < ActiveRecord::Base
    
  def file_object=(file_field)
    self.managed_file_object = file_field.read
    self.managed_file_name = base_part_of(file_field.original_filename)
    self.managed_file_mime = file_field.content_type.chomp
    self.managed_file_uri = file_field.path
    self.managed_file_size = file_field.size
    self.managed_file_status = 0
    self.managed_file_timestamp = Time.now.to_i
    # self.managed_file_time_to_leave = 5.hours.from_now.to_i
    self.managed_file_time_to_leave = 10.seconds.from_now.to_i
    self.managed_file_deleted = 0
    self.managed_file_parent_id = ((ManagedFile.last.try(:id)) || 0) + 1
    self.managed_file_user_id = 2
    self.managed_file_user_type = 2
  end

  def base_part_of file_name
    File.basename(file_name).gsub(/[^\w._-]/, '')
  end

  def save_using_block
    yield if block_given?
  end
end

app/models/managed_files_usage.rb
class ManagedFilesUsage < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :clear_expired_managed_files
  

  def clear_expired_managed_files
    expired_files = ManagedFile.where("managed_file_time_to_leave <= #{Time.now.to_i} AND managed_file_status = 0")
    if expired_files.length > 0
      expired_files.each do |expired_file|
        if expired_file.id = session[:file_id]
          session[:deleted] = 1
        end
        expired_file.destroy
      end
    end
  end
end

app/controllers/managed_files_controller.rb
class ManagedFilesController < ApplicationController
  before_action :set_managed_file, only: [:show, :edit, :update, :destroy, :uploaded_file]

  # GET /managed_files
  # GET /managed_files.json
  def index
    @managed_files = ManagedFile.all
  end

  # GET /managed_files/1
  # GET /managed_files/1.json
  def show
  end

  # GET /managed_files/new
  def new
    @managed_file = ManagedFile.new
  end

  # GET /managed_files/1/edit
  def edit
  end

  # POST /managed_files
  # POST /managed_files.json
  def create
    validated = false
    @managed_file = ManagedFile.new(file_object: managed_file_params[:file_object])
    @managed_file.save_using_block do
      unless @managed_file.managed_file_mime == "image/jpeg"
        redirect_with_validation_error_message ":::Invalid File."
      else
        validated = true
      end
    end

    save_file if validated
  end

  def save_file
    respond_to do |format|
      if @managed_file.save
        redirect_with_save_success_message format
      else
        redirect_with_save_error_message format
      end
    end
  end

  # PATCH/PUT /managed_files/1
  # PATCH/PUT /managed_files/1.json
  def update
    respond_to do |format|
      if @managed_file.update(file_object: managed_file_params[:file_object])
        format.html { redirect_to @managed_file, notice: 'Managed file was successfully updated.' }
        format.json { render :show, status: :ok, location: @managed_file }
      else
        format.html { render :edit }
        format.json { render json: @managed_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /managed_files/1
  # DELETE /managed_files/1.json
  def destroy
    ManagedFilesUsage.destroy_all("managed_file_id = #{@managed_file.id}")
    @managed_file.destroy
    session[:file_id] = nil
    respond_to do |format|
      format.html { redirect_to managed_files_url, notice: 'Managed file was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  def write_to_usage
    id = session[:file_id]
    unless id
      redirect_to managed_files_new_url, notice: ":::No File Chosen for saving."       
    else
      if session[:deleted] == 1
        redirect_to managed_files_new_url, notice: ":::Your session has expired. Please select a file again"
        session[:deleted] = nil
      else
        @managed_file = ManagedFile.find(id)
        @managed_file.update(managed_file_status: 1)
        model_id = (ManagedFilesUsage.last.try(:id) || 0) + 1
        if (ManagedFilesUsage.find_by(managed_file_id: id))
          @managed_files_usage = ManagedFilesUsage.find_by(managed_file_id: id)
          count = @managed_files_usage.count + 1
          @managed_files_usage.update(count: count)
          session[:file_id] = nil
          respond_to do |format|
            format.html { redirect_to managed_files_new_url, notice: ":::File Usage successfully Saved." }
            format.json { }
            format.js { }
          end
        else
          @managed_files_usage = ManagedFilesUsage.new(managed_file_id: session[:file_id], model: "Deal", model_id: model_id, count: 1)
          respond_to do |format|
            if @managed_files_usage.save
              session[:file_id] = nil
              format.html { redirect_to managed_files_new_url, notice: ":::File Usage successfully Saved." }
              format.json { }
              format.js { }
            else
              format.html { redirect_to managed_files_new_url, notice: ":::Save Unsuccessful..." }
              format.json { }
              format.js { }
            end
          end
        end
      end
    end
  end

  def redirect_with_save_success_message format
    format.html { redirect_to managed_files_path, notice: "File successfully uploaded." }
    # format.json { render :show, status: :created, location: @managed_file }
    # format.json { render text: ":::File #{@managed_file} successfully uploaded." }
    format.js {
      session[:file_id] = @managed_file.id
      @message = ":::File #{@managed_file.managed_file_name} successfully uploaded. Click submit below to complete upload."
    }
  end

  def redirect_with_save_error_message format
    format.html { render :new }
    format.json { render json: @managed_file.errors, status: :unprocessable_entity }
    format.js {
      @message = ":::Unable to upload file for now."
    }
  end

  def redirect_with_validation_error_message message
    respond_to do |format|
      format.html { redirect_to managed_files_path, notice: message }
      format.js {
        @message = message
      }
    end
  end

  def uploaded_file
    send_data(@managed_file.managed_file_object,
    filename: @managed_file.managed_file_name,
    type: @managed_file.managed_file_mime,
    disposition: "inline")
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_managed_file
      @managed_file = ManagedFile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def managed_file_params
      # params.require(:managed_file).permit(:managed_file)
      params[:managed_file]
    end
end

app/controllers/managed_files_usages_controller.rb
class ManagedFilesUsagesController < ApplicationController
  before_action :set_managed_file, only: [:models]

  def usage
    @managed_files_usage = ManagedFilesUsage.all
  end

  def models
    @models = ManagedFilesUsage.where("managed_file_id = #{@managed_file.id}")
  end

  private
    def set_managed_file
      @managed_file = ManagedFile.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/managed_files_helper.rb
module ManagedFilesHelper
end

app/helpers/managed_files_usages_helper.rb
module ManagedFilesUsagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FileManagement</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/managed_files/_form.html.erb
<%= form_for(@managed_file, url: managed_files_create_path, html: { method: :post, id: 'uploadForm', multipart: true, remote: true }) do |f| %>
  <% if @managed_file.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@managed_file.errors.count, "error") %> prohibited this managed_file from being saved:</h2>

      <ul>
      <% @managed_file.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :File %><br>
    <%= f.file_field :file_object %>
  </div>
  <div class="actions">
    <%= button_tag "Upload File", type: 'button', id: "upload" %>
    <!-- <div id="progress_bar" style="display: none;">
      .....................................................................................................
    </div> -->
    <progress style="display: none;"></progress>
    <input type="hidden" id="id" />
  </div>
  <div id="response" style="display:none;"> &nbsp; </div>
<% end %>
<div class="actions">
  <%= button_to "Submit", { controller: controller_name, action: :write_to_usage }, method: :post, data: {confirm: ":::Do you really want to proceed?"} %>
</div>

app/views/managed_files/create.js.erb
<%= escape_javascript render text: @message %>

app/views/managed_files/edit.html.erb
<h1>Editing Managed File</h1>

<%= render 'form' %>

<%= link_to 'Show', @managed_file %> |
<%= link_to 'Back', managed_files_path %>

app/views/managed_files/index.html.erb
<% if notice %>
  <p id="notice"><%= notice %></p>
<% end %>

<h1>Listing Managed Files</h1>

<table>
  <thead>
    <tr>
      <th>Managed file name</th>
      <th>Managed file uri</th>
      <th>Managed file mime</th>
      <th>Managed file size</th>
      <th>Managed file status</th>
      <th>Managed file timestamp</th>
      <th>Managed file time to leave</th>
      <th>Managed file deleted</th>
      <th>Managed file parent</th>
      <th>Managed file user</th>
      <th>Managed file user type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @managed_files.each do |managed_file| %>
      <tr>
        <td><%= managed_file.managed_file_name %></td>
        <td><%= managed_file.managed_file_uri %></td>
        <td><%= managed_file.managed_file_mime %></td>
        <td><%= managed_file.managed_file_size %></td>
        <td><%= managed_file.managed_file_status %></td>
        <td><%= managed_file.managed_file_timestamp %></td>
        <td><%= managed_file.managed_file_time_to_leave %></td>
        <td><%= managed_file.managed_file_deleted %></td>
        <td><%= managed_file.managed_file_parent_id %></td>
        <td><%= managed_file.managed_file_user_id %></td>
        <td><%= managed_file.managed_file_user_type %></td>
        <td><%= link_to 'Show', managed_file %></td>
        <td><%= link_to 'Models', { controller: "managed_files_usages", action: :models, id: managed_file.id }, method: :get %></td>
        <td><%= link_to 'Edit', edit_managed_file_path(managed_file) %></td>
        <td><%= link_to 'Destroy', managed_file, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Managed file', new_managed_file_path %>
<%= link_to 'Show File Usage', { controller: "managed_files_usages", action: :usage }, method: :get %>

app/views/managed_files/new.html.erb
<h1>New Managed File</h1>
<% if notice %>
  <p id="notice"><%= notice %></p>
<% end %>

<%= render 'form' %>

<%= link_to 'View All Files', managed_files_path %>

app/views/managed_files/show.html.erb
<% if notice %>
  <p id="notice"><%= notice %></p>
<% end %>

<p>
  <strong>Managed file name:</strong>
  <%= @managed_file.managed_file_name %>
</p>

<p>
  <strong>Managed file uri:</strong>
  <%= @managed_file.managed_file_uri %>
</p>

<%= link_to 'Edit', edit_managed_file_path(@managed_file) %> |
<%= link_to 'Back', managed_files_path %>

app/views/managed_files_usages/models.html.erb
<% if notice %>
  <p id="notice"><%= notice %></p>
<% end %>

<h1>Listing Managed Files Usage</h1>

<table>
  <thead>
    <tr>
      <th>Model Name</th>
      <th>Count</th>
    </tr>
  </thead>

  <tbody>
    <% @models.each do |managed_file_usage| %>
      <tr>
        <td><%= managed_file_usage.model %></td>
        <td><%= managed_file_usage.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Managed file', new_managed_file_path %>
<%= link_to 'Show File Usage', managed_files_usages_usage_url %>

app/views/managed_files_usages/usage.html.erb
<% if notice %>
  <p id="notice"><%= notice %></p>
<% end %>

<h1>Listing Managed Files Usage</h1>

<table>
  <thead>
    <tr>
      <th>Managed file name</th>
      <th>Model Name</th>
      <th>Count</th>
    </tr>
  </thead>

  <tbody>
    <% @managed_files_usage.each do |managed_file_usage| %>
      <tr>
        <% managed_file = ManagedFile.find(managed_file_usage.managed_file_id) %>
        <td><%= managed_file.managed_file_name %></td>
        <td><%= managed_file_usage.model %></td>
        <td><%= managed_file_usage.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Managed file', new_managed_file_path %>
<%= link_to 'Show Managed files', managed_files_url %>